name: gantry_mq_server
channels:
  - conda-forge
  - defaults
dependencies:
  # C/C++ requirements, pinning to older requirements for now
  - cmake=3.27
  - boost=1.82
  - gxx=12
  - fmt=10.0.0
  - pybind11
  # Required for a self-consistent version of glibc
  # - sysroot_linux-64=2.28 # Can be fixed by specifying LD_LIBRARY_PATH

  - wxwidgets # Requirments for DRS binding
  - libusb
  - libusb-compat
  # Setting up python dependencies required for server side objects
  - python=3.10
  - pyzmq
  - scipy
  - opencv
  - pyvisa-py
  - zeroconf
  - pyusb


